openapi: 3.0.0
info:
  title: Express Template API
  version: 1.0.0
paths:
  /:
    get:
      summary: Get request
      responses:
        '200':
          description: OK
    post:
      summary: Post request
      responses:
        '200':
          description: OK
